name: CI-CD.yml
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¢ ê¹ƒí—ˆë¸Œ checkout
        uses: actions/checkout@v3

      - name: ğŸ“¢ GitHubAction JDK 17 ì„¤ì¹˜
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: ğŸ“¢ Gradle ì‹¤í–‰ ê¶Œí•œ ë¶€ì—¬
        run: chmod +x gradlew

      - name: ğŸ“¢ Gradle ìºì‹±
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: ğŸ“¢ GitIgnore íŒŒì¼ë“¤ ë„£ì–´ì£¼ê¸°
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES}}
          EMAIL_PROPERTIES: ${{secrets.EMAIL_PROPERTIES}}
        run: |
          rm -f src/main/resources/application.properties
          rm -f src/main/resources/email.properties
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application.properties
          echo "${{ secrets.EMAIL_PROPERTIES }}" > src/main/resources/email.properties

      - name: ğŸ“¢ Gradle ë¹Œë“œ(war ë§Œë“¤ê¸°)
        run: ./gradlew clean build

      - name: ğŸ“¢ Docker image ë§Œë“¤ê¸°
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/zibi-backserver .

      - name: ğŸ“¢ DockerHubì— ë¡œê·¸ì¸
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_PASSWORD}}

      - name: ğŸ“¢ DockerHubì— PUSH
        run: docker push ${{ secrets.DOCKERHUB_USERNAME}}/zibi-backserver